<script>
    function disconnect() {
        const url = '<?php echo $this->getBaseUrl(); ?>/rest/V1/delete-prior-notify-token';
        var xhr = new XMLHttpRequest();
        xhr.open("POST", url, true);
        xhr.onreadystatechange = function() {
            if (this.readyState != 4) return;
            if (this.responseText === "\"success\"") {
                window.location.reload()
            }
        }
        xhr.send();
    }

    function connect() {
        localStorage.setItem('connect', 'true');
        const url = '<?php echo $this->getFrontUrl(); ?>/connect-magento?plugin_callback=<?php echo urlencode($this->getBaseUrl()); ?>';
        window.open(url, '_blank').focus();
    }
</script>
<?php if (!$this->getStatus()) { ?>
    <script>
        window.addEventListener('focus', focus);

        function focus(event) {
            const connected = localStorage.getItem('connect');
            if (connected === "true") {
                localStorage.removeItem('connect');
                const url = '<?php echo $this->getBaseUrl(); ?>/rest/V1/check-prior-notify-token';
                var xhr = new XMLHttpRequest();
                xhr.open("GET", url, true);
                xhr.onreadystatechange = function() {
                    if (this.readyState != 4) return;
                    if (this.responseText === "\"success\"") {
                        window.location.reload()
                    }
                }
                xhr.send();
            }
        }
    </script>
<?php } ?>

<div class="priorNotify__container">
    <div class="priorNotify__header">
        <div class="priorNotify__logo-wrapper">
            <img class="priorNotify__logo" src="<?php echo $this->getViewFileUrl('IncubatorLLC_PriorNotify::images/logo.png'); ?>" alt="PriorNotify" />
            <h1>PriorNotify plugin</h1>
        </div>
        <div>
        <?php if ($this->getStatus()) { ?>
            <div class="priorNotify__header-auth">
                <a class="btn-white" href='javascript:void(0)' onclick="disconnect()">Disconnect</a>
                <a class="btn-green" href="javascript:void(0)">Connected</a>
            </div>
        <?php } else { ?>
            <div class="priorNotify__header-auth">
                <a class="btn-blue" target="_blank" href="<?php echo $this->getFrontUrl(); ?>/register?redirect_uri=<?php echo $this->getBaseUrl(); ?>">Sign up</a>
                <a class="btn-blue" target="_blank" onclick="connect()" href="javascript:void(0)">Connect</a>
            </div>
        <?php } ?>
        </div>
    </div>
    <div class="instruction">
        <p class="bold">INSTRUCTIONS:</p>
        
        <p class="bold">A. SIGN UP button</p>
        
        <p>If you do not yet have a PriorNotify account, please press the SIGN UP button.</p>
        
        <p>Your first seven (7) days are free!</p>
        
        <p>A new browser tab will open to the 'Sign Up' page for the PriorNotify app.</p>
        
        <p class="bold">B. CONNECT button</p>
        
        <p>If you have a PriorNotify account, please press the CONNECT button.</p>
        
        <p>A new browser tab will open to the 'Log In' page for the PriorNotify app. You should enter your PriorNotify username and password in this page.</p>
        
        <p>Then, WooCommerce will ask for your authorization and approval to connect with your PriorNotify account. You should approve this request.</p>
        
        <p>That's it! You should then be connected with your PriorNotify account.</p>
    </div>
</div>
